services:
  db:
    image: postgres:16.0
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    env_file:
      - .env
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 1s
      retries: 5

  healthy_habits:
    build: .
    command: bash -c "python manage.py migrate && python manage.py collectstatic --noinput --clear && gunicorn --bind 0.0.0.0:8000 --workers 4 config.wsgi:application"
    env_file:
      - .env
    volumes:
      - ./static:/app/static/
    environment:
      POSTGRES_HOST: db
      REDIS_URL: "redis://redis:6379/1"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./static:/usr/share/nginx/html/static
    depends_on:
      - healthy_habits


  celery:
    build: .
    command: poetry run celery -A config worker -l INFO -P eventlet
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started


  celery-beat:
    build: .
    command: poetry run celery -A config beat -l INFO
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

networks:
  default:

volumes:
  postgres_data:
