# Generated by Django 5.2.1 on 2025-05-15 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(max_length=200, verbose_name="Место выполнения привычки")),
                ("time", models.TimeField(verbose_name="Время, когда необходимо выполнять привычку")),
                (
                    "action",
                    models.CharField(max_length=200, verbose_name="Действие, которое представляет собой привычка"),
                ),
                ("is_pleasant", models.BooleanField(default=False, verbose_name="Признак приятной привычки")),
                ("periodicity", models.PositiveIntegerField(default=1, verbose_name="Периодичность")),
                ("reward", models.CharField(blank=True, max_length=200, null=True, verbose_name="Вознаграждение")),
                ("time_complete", models.DurationField(verbose_name="Время на выполнение")),
                ("is_public", models.BooleanField(default=False, verbose_name="Признак публичности")),
                (
                    "associated_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель привычки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
