# Generated by Django 5.2.1 on 2025-05-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.DurationField(verbose_name="Время, когда необходимо выполнять привычку"),
        ),
    ]
